### ISSUE TITLE
FroalaEditorView license

### ISSUE THREAD

**Issue by tipoc123** [froala/react-froala-wysiwyg#231]
Do I need to pass config with a license (and attribution:false option) to the FroalaEditorView component?

**Comment by nratter** [comment]
@tipoc123 how did you work this out? I think this should be reopened.

**Comment by challet** [comment]
Wondering the same. With the same config as `FroalaEditor`, the former has a « Powered by Froala Editor » banner while the later hasn't.

**Comment by challet** [comment]
It is in fact because when editing without the right license, the edited content is outputted (and saved) with the attribution banner directly inside of it :/ Adding a new content when config is well set dosn"t lead to the same thing.

That also means old messages are stuck with it unless manually edited. Which is kind of ass design imho.
