### ISSUE TITLE
Error: Method undo.reset does not exist in Froala Editor.

### ISSUE THREAD

**Issue by ilangorajagopal** [froala/react-froala-wysiwyg#58]
I have multiple instances of Froala on a page. Users will have the option to remove any of the editor instance. When I try to remove an editor instance I get this error:

```
Error: Method undo.reset does not exist in Froala Editor. jquery.js:273
	error jquery.js:273
	a.fn.froalaEditor/< froala_editor.pkgd.min.js:7:5590
	each jquery.js:362
	each jquery.js:157
	a.fn.froalaEditor froala_editor.pkgd.min.js:7:5508
	t index.js:1:2995
	value index.js:1:3219
	value index.js:1:2756
	value index.js:1:2329
	commitLifeCycles react-dom.development.js:8806
	commitAllLifeCycles react-dom.development.js:9967
	callCallback react-dom.development.js:540
	invokeGuardedCallbackDev react-dom.development.js:579
	invokeGuardedCallback react-dom.development.js:436
	commitRoot react-dom.development.js:10071
	performWorkOnRoot react-dom.development.js:11003
	performWork react-dom.development.js:10952
	batchedUpdates react-dom.development.js:11070
	batchedUpdates react-dom.development.js:2323
	dispatchEvent react-dom.development.js:3414
	dispatchEvent self-hosted:997:17
```

I saw the same issue on [Froala for Angular repo](https://github.com/froala/angular-froala-wysiwyg/issues/79). I do have `initOnClick` set to true because there are many instances. I want to avoid setting it to false because there is also an option to dynamically add editor instances.. I'm using the latest version (2.7.3). Any help is appreciated. Also please tell me if you need more info.

**Comment by stefanneculai** [comment]
@ilangorajagopal would it be possible to setup a repo where we can see this problem? Thank you.

**Comment by stefanneculai** [comment]
@ilangorajagopal looking forward to details for this.

**Comment by topher515** [comment]
@ilangorajagopal I was seeing a similar when the parent of my `<FroalaEditor model={contentA} ... />` component re-rendered, and resulted in an entirely different model being given to my `<FroalaEditor model={contentB} ... />`. Because React doesn't know anything about the contentA or contentB it does a component update rather than component unmount / mount. React Froala doesn't seem to like this try adding the equivalent of `<FroalaEditor key={contentA.id} model={contentA}` and see if that fixes things.

**Comment by stefanneculai** [comment]
@topher515 could you please provide more details for us to check it?
