### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by leonardofaria** [froala/react-froala-wysiwyg#63]
Hi

Our QA team is facing a few problems trying to automate Froala wrapped by this component.

Background: 
- we use Watir (Ruby).
- doing some research we saw that we can do something like: `$.FroalaEditor.INSTANCES[0].$el.html('my content')", element)`. The issue here: because the editor is wrapped in a React component, `INSTANCES` is empty
- we saw a few examples showing `$("#editor")....` but I guess that this component doesn't take an id parameter.

That's said, any thoughts to share?
Thanks

**Comment by stefanneculai** [comment]
@leonardofaria what we would recommend is to use the manual initialization so that you have full control over the editor easier: https://github.com/froala/react-froala-wysiwyg#manual-instantiation. Also, it is good to set the HTML using the `html.set` method instead of accessing the instance DOM element.
